version: '3.8'

services:
  postgres:
    container_name: nest-pg-db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: nest-pg
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres

  cache:
    container_name: nest-cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
